### PR TITLE
Added spatial processing and prediction libraries

### PR DESCRIPTION
**Pull request by rapsoj**

### CODE REVIEW

**Comment by jayqi** [comment]
Hi @rapsoj,

The following packages that you requested are included in this commit: https://github.com/drivendataorg/water-supply-forecast-rodeo-runtime/commit/8123f9cd25b3fa845106df8587242d2fbdeeb3c1

- cpdsapi v0.6.1
- fiona v1.9.5
- pygrib v2.1.5
- pykrige v1.7.1
- pyproj v3.6.1
- shapely v2.0.2
- xagg v0.3.1

---

A few follow-up questions:

- You requested pysal v23.7. It looks like [PySAL](https://github.com/pysal/pysal) is a large meta-package that contains a lot of functionality, including interactive visualization libraries. Can you please clarify which specific packages included in PySAL that you are planning to use. As a note, aside from logging, you generally will not be getting any feedback from your code submission runs. If you are planning to do more interactive evaluation of your model runs, you should do so locally without us adding dependencies for that to the evaluation runtime. 
- You requested reportlab v4.0.7. reportlab looks to be a package for generating PDF files. Can you please clarify how you are using this?
- You requested shap v0.42.1. Can you please clarify how you are using this package? Per my previous point, you should do your model evaluation locally without us adding dependencies for it to the evaluation runtime. 
- You requested torch v2.1.1. Can you please clarify what this is? There is no conda package on conda-forge named torch. Do you mean to request PyTorch, which is named torch on PyPI? We include pytorch 1.13.1 in the environment already. Will your code work with version 1.13.1 or do you need v2.1.1 specifically? 
- You requested xagg v0.3.1.1. Currently, v0.3.1 is the latest available. There is an open PR on the xagg feedstock repository for v0.3.1.1: https://github.com/conda-forge/xagg-feedstock/pull/16 Do you need v0.3.1.1 specifically, or is v0.3.1 sufficient? If you require v0.3.1.1, and the maintainer is not able to release v0.3.1.1 on conda-forge in a timely manner, we can explore installing through pip from PyPI.

**Comment by rapsoj** [comment]
Hi @jayqi , 

To respond to your questions:

pysal v23.7 – This is intended to be used primarily for feature engineering and spatial modelling; the packages we specifically intend to use are [libpysal](https://pysal.org/libpysal/), [esda](https://pysal.org/notebooks/explore/esda/Spatial_Autocorrelation_for_Areal_Unit_Data.html), [spreg](https://github.com/pysal/spreg), [giddy](https://pysal.org/notebooks/explore/giddy/intro.html), and [pointpats](https://github.com/pysal/pointpats) (spatial autocorrelation from point data)

reportlab v4.0.7 – This was included as I was unclear whether the dependencies requested in this section would also be used for the explainability portion of the challenge; if we do not need to produce explainable results that can be interpreted by practitioners for this section, then please ignore this request

shap v0.42.1 – Same as above

torch v2.1.1 – Please ignore, pytorch 1.13.1 is sufficient

xagg v0.3.1.1 – Please ignore, xagg 0.3.1 is sufficient

**Comment by jayqi** [comment]
Hi @rapsoj,

The individual packages from PySAL that you listed have been added to the runtime environment as of [this commit](https://github.com/drivendataorg/water-supply-forecast-rodeo-runtime/commit/ee2d63116c80918cf9b755b98bdb9c95a77067b8). 

Regarding xagg, I will see if we get any update from the xagg feedstock maintainer. If not, then I will look into installation through pip.

It looks like I forgot to address `ee=0.2` in your original PR change. Can you please clarify what this package is? There does not appear to be an ee package on conda-forge, and the [ee package on PyPI](https://pypi.org/project/ee/) does not look obviously relevant to the competition. Is this supposed to be earthengine-api? I believe your team submitted a data approval request that involved some data sources from Google Earth Engine. If so, please see my response email—it may be the case that we will not be able to approve any Earth Engine data sources for this competition.

**Comment by rapsoj** [comment]
Hi @jayqi , ee is the Earth Engine API. If it is not usable for this competition, please also ignore that request.

**Comment by jayqi** [comment]
Hi @rapsoj, I was able to work with the xagg feedstock maintainer to get v0.3.1.1 released. It's included in the image as of [this commit](https://github.com/drivendataorg/water-supply-forecast-rodeo-runtime/commit/2c8889b4c31ed6b10d66a90eb4fb1ec0016bab3e). I believe all of the packages you requested here have been incorporated, so I'm closing this PR. Let me know if you have any questions.

**Pull request closed without merging**
